# UltraMCP ContextBuilderAgent 2.0 - Persistent Storage
# Production-grade storage for stateful services

---
# PostgreSQL Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: contextbuilder-ssd
  hostPath:
    path: /data/contextbuilder/postgres
    type: DirectoryOrCreate

---
# Redis Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: contextbuilder-ssd
  hostPath:
    path: /data/contextbuilder/redis
    type: DirectoryOrCreate

---
# Prometheus Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: contextbuilder-ssd
  hostPath:
    path: /data/contextbuilder/prometheus
    type: DirectoryOrCreate

---
# Grafana Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: contextbuilder-ssd
  hostPath:
    path: /data/contextbuilder/grafana
    type: DirectoryOrCreate

---
# Context Data Persistent Volume (for .context directory)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: context-data-pv
  labels:
    app.kubernetes.io/name: context-data
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: contextbuilder
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: contextbuilder-nfs
  hostPath:
    path: /data/contextbuilder/context
    type: DirectoryOrCreate

---
# Storage Class for SSD storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: contextbuilder-ssd
  labels:
    app.kubernetes.io/name: storage-class
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: contextbuilder
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true

---
# Storage Class for shared NFS storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: contextbuilder-nfs
  labels:
    app.kubernetes.io/name: storage-class-nfs
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: contextbuilder
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true