# UltraMCP ContextBuilderAgent 2.0 - Persistent Volume Claims
# Storage claims for stateful services

---
# PostgreSQL Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: contextbuilder-ssd
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql

---
# Redis Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: contextbuilder-ssd
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: redis

---
# Prometheus Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: contextbuilder-ssd
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus

---
# Grafana Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: contextbuilder-ssd
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana

---
# Context Data Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: context-data-pvc
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: context-data
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: contextbuilder
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: contextbuilder-nfs
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: context-data