# UltraMCP ContextBuilderAgent 2.0 - Database Secrets
# Secure credentials for database services

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: database-secrets
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: contextbuilder
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  postgres-user: Y29udGV4dGJ1aWxkZXI=  # contextbuilder
  postgres-password: Y29udGV4dGJ1aWxkZXJfc2VjdXJlXzIwMjQ=  # contextbuilder_secure_2024
  postgres-database: Y29udGV4dGJ1aWxkZXI=  # contextbuilder
  
  # Redis credentials (base64 encoded)
  redis-password: Y29udGV4dGJ1aWxkZXJfcmVkaXNfMjAyNA==  # contextbuilder_redis_2024
  
  # Connection URLs (base64 encoded)
  postgres-url: cG9zdGdyZXNxbDovL2NvbnRleHRidWlsZGVyOmNvbnRleHRidWlsZGVyX3NlY3VyZV8yMDI0QHBvc3RncmVzOjU0MzIvY29udGV4dGJ1aWxkZXI=  # postgresql://contextbuilder:contextbuilder_secure_2024@postgres:5432/contextbuilder
  redis-url: cmVkaXM6Ly86Y29udGV4dGJ1aWxkZXJfcmVkaXNfMjAyNEByZWRpczozNzk=  # redis://:contextbuilder_redis_2024@redis:6379

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: monitoring-secrets
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: contextbuilder
type: Opaque
data:
  # Grafana admin credentials (base64 encoded)
  grafana-admin-user: YWRtaW4=  # admin
  grafana-admin-password: Y29udGV4dGJ1aWxkZXJfZ3JhZmFuYV8yMDI0  # contextbuilder_grafana_2024
  
  # Alertmanager credentials (base64 encoded)
  alertmanager-webhook-secret: d2ViaG9va19zZWNyZXRfMjAyNA==  # webhook_secret_2024