version: '3.8'

services:
  # Simple UltraMCP Agent Registry (no database dependencies)
  simple-agent-registry:
    build: ./services/simple-agent-registry
    container_name: ultramcp-simple-agent-registry
    restart: unless-stopped
    ports:
      - "7778:7778"
    environment:
      - PORT=7778
      - PLANDEX_BINARY=/usr/local/bin/plandex
      - NODE_ENV=production
    volumes:
      - ./data/registry:/data
      - ./logs:/logs
      - /usr/local/bin/plandex:/usr/local/bin/plandex:ro
      - ./workspace:/workspace
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7778/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  plandex-workspace:
    driver: local