# UltraMCP ContextBuilderAgent 2.0 - PostgreSQL ConfigMap
# PostgreSQL Configuration for Kubernetes

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: "15"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
data:
  POSTGRES_DB: contextbuilder
  POSTGRES_USER: contextbuilder
  POSTGRES_PASSWORD: contextbuilder_secure_2024
  
  postgresql.conf: |
    # PostgreSQL Configuration for ContextBuilderAgent 2.0
    
    # Connection Settings
    listen_addresses = '*'
    port = 5432
    max_connections = 200
    
    # Memory Configuration
    shared_buffers = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 64MB
    work_mem = 4MB
    
    # Checkpoint Configuration
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    min_wal_size = 1GB
    max_wal_size = 4GB
    
    # Query Planner
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    # Parallel Query
    max_worker_processes = 8
    max_parallel_workers_per_gather = 4
    max_parallel_workers = 8
    max_parallel_maintenance_workers = 4
    
    # Logging
    log_destination = 'stderr'
    log_statement = 'all'
    log_min_duration_statement = 1000
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    log_temp_files = 0
    log_autovacuum_min_duration = 0
    
    # Extensions
    shared_preload_libraries = 'pg_stat_statements'
    
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration
    
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 md5
    host    all             all             0.0.0.0/0               md5