# UltraMCP ContextBuilderAgent 2.0 - Redis ConfigMap
# Redis Configuration for Kubernetes

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: "7"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
data:
  redis.conf: |
    # Redis Configuration for ContextBuilderAgent 2.0
    bind 0.0.0.0
    port 6379
    protected-mode yes
    requirepass contextbuilder_redis_2024
    
    # Memory Configuration
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec
    
    # Performance
    tcp-keepalive 300
    timeout 0
    databases 16
    
    # Stream Configuration (for Semantic Coherence Bus)
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    
    # Pub/Sub optimization
    client-output-buffer-limit pubsub 32mb 8mb 60
    
    # Logging
    loglevel notice
    
    # Security
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command CONFIG ""
    rename-command DEBUG ""