# Configuración de Prometheus para MCP Enterprise
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mcp-enterprise'
    environment: 'production'

# Configuración de reglas de alertas
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Configuración de Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuración de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['sam.chat:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # MCP Backend
  - job_name: 'mcp-backend'
    static_configs:
      - targets: ['mcp_backend:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (sistema)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Docker Exporter
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s

  # Webhook Receiver
  - job_name: 'mcp-webhooks'
    static_configs:
      - targets: ['mcp_webhooks:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Notification Protocol
  - job_name: 'mcp-notifications'
    static_configs:
      - targets: ['mcp_notifications:8766']
    metrics_path: /metrics
    scrape_interval: 30s

  # Memory Analyzer
  - job_name: 'mcp-memory'
    static_configs:
      - targets: ['mcp_memory:8767']
    metrics_path: /metrics
    scrape_interval: 30s

# Configuración de almacenamiento
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Configuración de logging
log_level: info
log_format: json

