# UltraMCP ContextBuilderAgent 2.0 - Database Services
# Kubernetes Services for PostgreSQL and Redis

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: "15"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: "7"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database

---
# Redis Sentinel Service
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: redis-sentinel
    app.kubernetes.io/version: "7"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis-sentinel
    app.kubernetes.io/component: database

---
# PgBouncer Service (Connection Pooler)
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
      protocol: TCP
  selector:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database