# UltraMCP ContextBuilderAgent 2.0 - Monitoring Services
# Kubernetes Services for Prometheus, Grafana, and monitoring stack

---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring

---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring

---
# Alertmanager Service
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: monitoring

---
# Node Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/component: monitoring

---
# Custom Metrics Collector Service
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  namespace: contextbuilder
  labels:
    app.kubernetes.io/name: metrics-collector
    app.kubernetes.io/version: "2.0"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: contextbuilder
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: metrics-collector
    app.kubernetes.io/component: monitoring