# UltraMCP ContextBuilderAgent 2.0 - Alertmanager Configuration
# Production Alert Management and Notification

global:
  smtp_smarthost: 'sam.chat:587'
  smtp_from: 'alerts@contextbuilder.local'
  smtp_auth_username: 'alerts@contextbuilder.local'
  smtp_auth_password: 'contextbuilder_alerts_2024'

# Template files
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
      
    # ContextBuilder specific alerts
    - match:
        team: contextbuilder
      receiver: 'contextbuilder-team'
      group_interval: 5m
      repeat_interval: 30m
      
    # Infrastructure alerts
    - match:
        team: infrastructure
      receiver: 'infrastructure-team'
      group_interval: 15m
      repeat_interval: 1h
      
    # Performance alerts
    - match_re:
        alertname: '.*Performance.*|.*Slow.*|.*High.*'
      receiver: 'performance-alerts'
      group_interval: 10m
      repeat_interval: 45m

# Inhibition rules to prevent alert spam
inhibit_rules:
  # Inhibit any alert if service is down
  - source_match:
      alertname: 'ContextBuilderServiceDown'
    target_match_re:
      service: '.*'
    equal: ['service']
    
  # Inhibit performance alerts if system is down
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['instance']

# Alert receivers and notification channels
receivers:
  - name: 'default'
    email_configs:
      - to: 'admin@contextbuilder.local'
        subject: 'ContextBuilderAgent Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          
          {{ range .Alerts }}
          Instance: {{ .Labels.instance }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'critical@contextbuilder.local'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Please investigate immediately!
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#critical-alerts'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: 'danger'

  - name: 'contextbuilder-team'
    email_configs:
      - to: 'contextbuilder-team@contextbuilder.local'
        subject: 'ContextBuilderAgent Alert: {{ .GroupLabels.alertname }}'
        body: |
          ContextBuilderAgent Team Alert
          =============================
          
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          Team: {{ .CommonLabels.team }}
          
          {{ range .Alerts }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Labels:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#contextbuilder-alerts'
        title: 'ContextBuilderAgent Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'

  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@contextbuilder.local'
        subject: 'Infrastructure Alert: {{ .GroupLabels.alertname }}'
        body: |
          Infrastructure Team Alert
          =========================
          
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          Team: {{ .CommonLabels.team }}
          
          {{ range .Alerts }}
          Instance: {{ .Labels.instance }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'performance-alerts'
    email_configs:
      - to: 'performance@contextbuilder.local'
        subject: 'Performance Alert: {{ .GroupLabels.alertname }}'
        body: |
          Performance Alert
          =================
          
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          
          {{ range .Alerts }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Metrics:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

# Webhook configurations for external systems
  - name: 'webhook-alerts'
    webhook_configs:
      - url: 'http://sam.chat:8028/api/observatory/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'contextbuilder'
            password: 'webhook_secret_2024'
        max_alerts: 10

# PagerDuty integration for critical alerts
  - name: 'pagerduty-critical'
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }}'
        details:
          alert_count: '{{ len .Alerts }}'
          status: '{{ .Status }}'
          severity: '{{ .CommonLabels.severity }}'

# Microsoft Teams integration
  - name: 'teams-alerts'
    webhook_configs:
      - url: 'https://outlook.office.com/webhook/YOUR/TEAMS/WEBHOOK'
        send_resolved: true
        title: 'ContextBuilderAgent Alert'
        text: |
          {{ range .Alerts }}
          **{{ .Annotations.summary }}**
          {{ .Annotations.description }}
          {{ end }}

# Custom notification script
  - name: 'custom-script'
    webhook_configs:
      - url: 'http://sam.chat:8999/custom-alert-handler'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'contextbuilder'
            password: 'custom_handler_2024'