const { createClient } = require("@supabase/supabase-js");

// Load environment variables from .env file
require("dotenv").config({ path: require("path").resolve(__dirname, "../../.env") });

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error("Supabase URL or Key is not defined. Make sure SUPABASE_URL and SUPABASE_KEY are set in your .env file.");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function setupDatabase() {
  console.log("Starting database setup using direct SQL execution...");

  try {
    // SQL for creating command_logs table
    const createCommandLogsTableSql = `
      CREATE TABLE IF NOT EXISTS public.command_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        command TEXT NOT NULL,
        status TEXT NOT NULL,
        output TEXT,
        error TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `;
    console.log("Attempting to create command_logs table...");
    const { error: commandLogsError } = await supabase.rpc("execute_sql_statement", { sql_query: createCommandLogsTableSql });
    if (commandLogsError) {
      console.error("Error creating command_logs table:", commandLogsError.message);
    } else {
      console.log("command_logs table creation statement executed (check Supabase for actual status).");
    }

    // SQL for creating credentials table
    const createCredentialsTableSql = `
      CREATE TABLE IF NOT EXISTS public.credentials (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        service TEXT NOT NULL,
        key TEXT NOT NULL,
        value TEXT NOT NULL, -- Encrypted value
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE (service, key)
      );
    `;
    console.log("Attempting to create credentials table...");
    const { error: credentialsError } = await supabase.rpc("execute_sql_statement", { sql_query: createCredentialsTableSql });

    if (credentialsError) {
      console.error("Error creating credentials table:", credentialsError.message);
    } else {
      console.log("credentials table creation statement executed (check Supabase for actual status).");
    }

    // SQL for creating the trigger function and trigger
    const createTriggerSql = `
      CREATE OR REPLACE FUNCTION public.trigger_set_timestamp()
      RETURNS TRIGGER AS $$
      BEGIN
        NEW.updated_at = NOW();
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;

      DROP TRIGGER IF EXISTS set_credentials_timestamp ON public.credentials;
      CREATE TRIGGER set_credentials_timestamp
      BEFORE UPDATE ON public.credentials
      FOR EACH ROW
      EXECUTE FUNCTION public.trigger_set_timestamp();
    `;
    console.log("Attempting to create/update trigger for credentials table...");
    const { error: triggerError } = await supabase.rpc("execute_sql_statement", { sql_query: createTriggerSql });
    if (triggerError) {
      console.error("Error creating trigger for credentials table:", triggerError.message);
    } else {
      console.log("Trigger creation/update statement executed (check Supabase for actual status).");
    }

    console.log("Database setup script finished. Please verify table creation in Supabase.");

  } catch (error) {
    console.error("Error during database setup:", error);
  }
}

setupDatabase();

